[build]
  base = "frontend"       # Your frontend folder
  command = "pnpm run build"
  publish = "dist"        # Vite build output folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


